# spelling.py

GERMAN = {
    "A": "Anton",
    "B": "Berta",
    "C": "Cäsar",
    "D": "Dora",
    "E": "Emil",
    "F": "Friedrich",
    "G": "Gustav",
    "H": "Heinrich",
    "I": "Ida",
    "J": "Julius",
    "K": "Kaufmann",
    "L": "Ludwig",
    "M": "Martha",
    "N": "Nordpol",
    "O": "Otto",
    "P": "Paula",
    "Q": "Quelle",
    "R": "Richard",
    "S": "Samuel",
    "SCH": "Schule",
    "T": "Theodor",
    "U": "Ulrich",
    "V": "Viktor",
    "W": "Wilhelm",
    "X": "Xanthippe",
    "Y": "Ypsilon",
    "Z": "Zacharias",
    "Ä": "Ärger",
    "Ö": "Ökonom",
    "Ü": "Übermut",
    "0": "Null",
    "1": "Eins",
    "2": "Zwei",
    "3": "Drei",
    "4": "Vier",
    "5": "Fünf",
    "6": "Sechs",
    "7": "Sieben",
    "8": "Acht",
    "9": "Neun",
    " ": "Leerzeichen",
    ".": "Punkt",
    ",": "komma",
    ";": "Semikolon",
    ":": "DoppelPunkt",
    "?": "Fragezeichen",
    "!": "Ausrufezeichen",
    "@": "At-Zeichen",
    "&": "Und-Zeichen",
    '"': "Anführungszeichen",
    "'": "Apostroph",
    "-": "Bindestrich",
    "/": "Schrägstrich",
    "\\": "Umgekehrter-Schrägstrich",
    "(": "Runde-Klammer-links",
    ")": "Runde-Klammer-rechts",
    "[": "Eckige-Klammer-links",
    "]": "Eckige-Klammer-rechts",
    "{": "Geschweifte-Klammer-links",
    "}": "Geschweifte-Klammer-rechts",
    "<": "Kleiner-als-Zeichen",
    ">": "Größer-als-Zeichen",
    "|": "Senkrechter-Strich",
    "°": "Gradzeichen",
    "*": "Sternchen",
    "+": "Pluszeichen",
    "=": "Gleichheitszeichen",
    "#": "Rautenzeichen",
    "§": "Paragraphenzeichen",
    "$": "Dollarzeichen",
    "€": "Euro-Zeichen",
    "~": "Tilde",
    "_": "Unterstrich",
    "%": "Prozentzeichen",
    "^": "Zirkumflex",
}

INTERNATIONAL = {
    "A": "Alfa",
    "B": "Bravo",
    "C": "Charlie",
    "D": "Delta",
    "E": "Echo",
    "F": "Foxtrot",
    "G": "Golf",
    "H": "Hotel",
    "I": "India",
    "J": "Juliett",
    "K": "Kilo",
    "L": "Lima",
    "M": "Mike",
    "N": "November",
    "O": "Oscar",
    "P": "Papa",
    "Q": "Quebec",
    "R": "Romeo",
    "S": "Sierra",
    "T": "Tango",
    "U": "Uniform",
    "V": "Victor",
    "W": "Whiskey",
    "X": "X-ray",
    "Y": "Yankee",
    "Z": "Zulu",
    "0": "Zero",
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine",
    " ": "Space",
    ".": "Dot",
    ",": "Comma",
    ";": "Semicolon",
    ":": "Colon",
    "?": "Question-Mark",
    "!": "Exclamation-Mark",
    "@": "At-Sign",
    "&": "Ampersand",
    '"': "Double-Quotation-Mark",
    "'": "Single-Quotation-Mark",
    "-": "Minus-Sign",
    "/": "Forward-Slash",
    "\\": "Backslash",
    "(": "Left-Round-Bracket",
    ")": "Right-Round-Bracket",
    "[": "Left-Square-Bracket",
    "]": "Right-Square Bracket",
    "{": "Left-Curly-Bracket",
    "}": "Right-Curly-Bracket",
    "<": "Less-Than-Sign",
    ">": "Greater-Than-Sign",
    "|": "Pipe",
    "°": "Degree-Symbol",
    "*": "Star",
    "+": "Plus-Sign",
    "=": "Equal-Sign",
    "#": "Hash",
    "§": "Section-Sign",
    "$": "Dollar-Sign",
    "€": "Euro-Sign",
    "~": "Tilde",
    "_": "Underscore",
    "%": "Percent-Sign",
    "^": "Caret",
}

SPELLING = {"German": GERMAN, "International": INTERNATIONAL}


def spell_word(text: str, lang: str) -> str:
    mapping = SPELLING[lang]
    return " ".join(mapping.get(ch.upper(), "??") for ch in text)
